# Generated by Django 5.0.6 on 2024-07-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='color',
        ),
    ]
