# Generated by Django 5.0.6 on 2024-06-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_category_remove_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], default='Low', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'TO_DO'), ('AWAIT_FEEDBACK', 'AWAIT_FEEDBACK'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE')], default='TO_DO', max_length=15),
        ),
    ]
